// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://picqunlrqgxrlclhqdfs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpY3F1bmxycWd4cmxjbGhxZGZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3NzA5MzcsImV4cCI6MjA3MTM0NjkzN30.Xjx0T6BmEbSLHVeX8-iJqD_RVoIsyfxjeoi95JAR03o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});